// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Analyse: typeof import('./components/views/Analyse.vue')['default']
    Audit: typeof import('./components/views/Audit.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    CodeView: typeof import('./components/views/codeView.vue')['default']
    CostDriverAssess: typeof import('./components/views/costDriverAssess.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Estimate: typeof import('./components/views/estimate.vue')['default']
    HelloWorld: typeof import('./components/views/HelloWorld.vue')['default']
    Home: typeof import('./components/views/Home.vue')['default']
    Login: typeof import('./components/views/Login.vue')['default']
    Logout: typeof import('./components/views/Logout.vue')['default']
    Menu: typeof import('./components/views/Menu.vue')['default']
    PersonView: typeof import('./components/views/personView.vue')['default']
    Project_list: typeof import('./components/views/project_list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/views/Search.vue')['default']
    SearchProject: typeof import('./components/views/search-project.vue')['default']
  }
}

export {}
